apiVersion: 0.0.1
kind: ComponentConfig
spec:
  inbound:
    - name: rupiyal-bff
      port: 8080
      type: REST
      networkVisibility: Public
      context: /
      schemaFilePath: openapi.yaml
  outbound:
    serviceReferences:
    - name: choreo:///lkrexchange/core/hoyqdy/5c69c/v1.0/ORGANIZATION
      connectionConfig: 01ef0539-2099-1cd8-9c4f-51c4902e4bb4
      env:
      - from: ServiceURL
        to: CORE_API_SERVICE_URL
      - from: ConsumerKey
        to: CORE_API_OAUTH_CLIENT_ID
      - from: ConsumerSecret
        to: CORE_API_OAUTH_CLIENT_SECRET
      - from: TokenURL
        to: CORE_API_OAUTH_TOKEN_URL